# Setup
title:        FCM/FEnf Unicamp
tagline:      Documentações e orientações sobre os módulos
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Newton da Silva
  url:        https://github.com/newtondasilva

author2:
  name:       João Pedro Mantovani
  url:        https://github.com/joaomantovani

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
# theme: jekyll-theme-cayman